version: "3"
services:
  mysql:
    container_name: cocoon_mysql ## 要変更
    build:
      context: ./
      dockerfile: ./build/mysql/Dockerfile.dev
    ports:
      - 4306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cocoon ## 要変更
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default

  server:
    container_name: cocoon_server
    build:
      context: ./
      dockerfile: ./build/server/Dockerfile.dev
    ports:
      - 8000:80
    volumes:
      - ./themes/cocoon:/var/www/html/wp-content/themes/cocoon # 要変更
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: cocoon ## 要変更
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - default

networks:
  default:
    external: false
volumes:
  mysql-data:
