version: "3"
services:
  mysql:
    container_name: wp_mysql ## 要変更
    build:
      context: ./
      dockerfile: build/mysql/Dockerfile.dev
    ports:
      - 4306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: .env
    networks:
      - default

  server:
    container_name: wp_server ## 要変更
    build:
      context: ./
      dockerfile: build/server/Dockerfile.dev
    ports:
      - 8000:80
    volumes:
      - ./.plugins/advanced-custom-fields:/var/www/html/wp-content/plugins/advanced-custom-fields ## 要変更
      - ./.themes/the-blank:/var/www/html/wp-content/themes/the-blank ## 要変更
      - ./the-blank-child:/var/www/html/wp-content/themes/the-blank-child ## 要変更
    env_file: .env
    depends_on:
      - mysql
    networks:
      - default

networks:
  default:
    external: false
volumes:
  mysql-data:
